export type SkillNode = {
  id: string
  treeId: string
  title: string
  subtitle: string
  level: number
  track: 'foundation' | 'secondary' | 'top-game'
  prerequisites: string[]
  description: string
  why: string
  successDefinition: string[]
  videos: {
    title: string
    url: string
    creator: string
    note?: string
  }[]
  drill: string
  sparringFocus: string
  commonErrors: string[]
  completionRules: {
    id: string
    label: string
  }[]
  validationQuestion?: string
  validationOptions?: string[]
  validationCorrectAnswer?: string
  isComingSoon?: boolean
}

export const LONG_FLEXIBLE_GUARD_TREE: SkillNode[] = [
  {
    id: 'node-1-guard-identity',
    treeId: 'long-flexible-guard',
    title: 'Guard Identity',
    subtitle: 'Verstehe deinen Stil',
    level: 1,
    track: 'foundation',
    prerequisites: [],
    description: 'Du definierst deinen Win Path und verstehst, warum Guard-Retention, Winkel und Backtakes dein Kernspiel sind.',
    why: 'Ohne Identitaet trainierst du zufaellige Techniken. Mit Identitaet baust du ein System.',
    successDefinition: ['Du kannst deinen Archetyp erklaeren', 'Du kennst deinen Win Path', 'Du verstehst DLR und K-Guard als Hauptsysteme'],
    videos: [
      { title: 'Guard Identity', url: 'https://www.youtube.com/watch?v=mcU5FBy9n7s', creator: 'YouTube' },
      {
        title: 'Shin-to-Shin Reel',
        url: 'https://www.instagram.com/reel/DTr_HxIiTUj/',
        creator: 'SEBASTIAN ATTARD',
      },
      {
        title: 'Shin-to-Shin Details',
        url: 'https://www.instagram.com/reel/DP5CAGrCBpt/',
        creator: 'Robert Hastings',
      },
      {
        title: 'Simple Shin-to-Shin Entry',
        url: 'https://www.instagram.com/reel/DP6sLXMDs_U/',
        creator: 'Simple Man Martial Arts',
      },
      { title: 'How to Build Your BJJ Gameplan', url: 'https://www.youtube.com/watch?v=X3cPYqn-3jM', creator: 'Chewjitsu' },
    ],
    drill: 'Schreibe deinen Win Path auf und sage ihn vor jeder Einheit einmal laut auf.',
    sparringFocus: 'Beobachte in drei Runden, welche Positionen du natuerlich suchst und ob sie zu deinem Archetyp passen.',
    commonErrors: ['Zu viele Guards gleichzeitig lernen', 'Keine klare Reihenfolge im Training'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'written', label: 'Win Path notiert' },
    ],
    validationQuestion: 'Was ist das Hauptziel von Guard Identity?',
    validationOptions: [
      'Deinen Win Path klar definieren',
      'Schneller in die Guard fallen',
      'Mehr Submissions sammeln',
      'Nur Sweeps trainieren',
    ],
    validationCorrectAnswer: 'Deinen Win Path klar definieren',
  },
  {
    id: 'node-2-guard-entry',
    treeId: 'long-flexible-guard',
    title: 'Guard Entry',
    subtitle: 'Sicher in die Guard kommen',
    level: 2,
    track: 'foundation',
    prerequisites: ['node-1-guard-identity'],
    description: 'Du lernst sichere Grips, Distanzmanagement und einen Guard Pull mit sofortiger Connection.',
    why: 'Ohne sauberen Entry kommt dein A-Game gar nicht erst zustande.',
    successDefinition: ['Grip vor dem Pull', 'Kontrollierte Landung auf der Seite', 'Sofortiger erster Hook oder Frame'],
    videos: [
      { title: 'Guard Pull Mechanics', url: 'https://www.youtube.com/watch?v=TUbGnOKQ2Ck', creator: 'Lachlan Giles' },
      { title: 'Distance Management for Guard Players', url: 'https://www.youtube.com/watch?v=bzCpEblbfDE', creator: 'Gordon Ryan' },
    ],
    drill: '3 x 2 Minuten Guard Pull mit Grip zuerst, dann sauberer Winkel auf der Seite.',
    sparringFocus: 'In drei Runden nur den Entry priorisieren, nicht sofort den Sweep.',
    commonErrors: ['Erst fallen, dann Grips suchen', 'Zu nah zum Gegner', 'Flach auf dem Ruecken landen'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'drilled', label: 'Entry-Drill absolviert' },
      { id: 'attempted', label: 'Entry im Sparring versucht' },
    ],
    validationQuestion: 'Was kommt beim Guard Entry zuerst?',
    validationOptions: [
      'Grips sichern und Distanz kontrollieren',
      'Sofort auf den Ruecken fallen',
      'Den Gegner ziehen ohne Verbindung',
      'Direkt den Sweep versuchen',
    ],
    validationCorrectAnswer: 'Grips sichern und Distanz kontrollieren',
  },
  {
    id: 'node-3-dlr-connection',
    treeId: 'long-flexible-guard',
    title: 'DLR Connection',
    subtitle: 'Saubere De La Riva Verbindung',
    level: 3,
    track: 'foundation',
    prerequisites: ['node-2-guard-entry'],
    description: 'Hook, Grip, Hips und Distanz fuer eine stabile DLR-Grundposition.',
    why: 'Ohne saubere Verbindung ist DLR nur eine Idee, aber keine kontrollierte Guard.',
    successDefinition: ['Hook sitzt sauber', 'Innerer Arm kontrolliert', 'Seitlicher Winkel bleibt stabil'],
    videos: [
      { title: 'De La Riva Guard Fundamentals', url: 'https://www.youtube.com/watch?v=HgmACpVVCQI', creator: 'Bernardo Faria' },
      { title: 'DLR Connection and Grip Fighting', url: 'https://www.youtube.com/watch?v=9kZpCTRWxq0', creator: 'Mikey Musumeci' },
    ],
    drill: '5 x 2 Minuten DLR-Hook setzen, halten und nach jeder Stoerung sofort wiederfinden.',
    sparringFocus: 'Zaehle, wie oft du die DLR-Connection fuer mehr als 5 Sekunden sauber haeltst.',
    commonErrors: ['Zu flach liegen', 'Kein Aermelgrip', 'Gegner zu nah heranlassen'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'drilled', label: '5 Drill-Runden absolviert' },
      { id: 'attempted', label: 'DLR im Sparring genutzt' },
    ],
    validationQuestion: 'Was darf bei DLR nie fehlen?',
    validationOptions: [
      'Ein sauber gesetzter Hook',
      'Beide Beine geschlossen',
      'Kein Griffkontakt',
      'Flach auf dem Ruecken liegen',
    ],
    validationCorrectAnswer: 'Ein sauber gesetzter Hook',
  },
  {
    id: 'node-4-dlr-retention',
    treeId: 'long-flexible-guard',
    title: 'DLR Retention',
    subtitle: 'Guard behalten unter Druck',
    level: 4,
    track: 'foundation',
    prerequisites: ['node-3-dlr-connection'],
    description: 'Du lernst Frames, Hip-Angles und Recovery, wenn dein Gegner den Hook angreift.',
    why: 'Retention ist die Bruecke zwischen Position haben und Position wirklich nutzen.',
    successDefinition: ['Hook recovern', 'Frames gegen Vorwaertsdruck setzen', 'DLR nach Stoerung erneut etablieren'],
    videos: [{ title: 'Guard Retention Principles', url: 'https://www.youtube.com/watch?v=IdXJr3F1AH0', creator: 'Priit Mihkelson' }],
    drill: '3 x 3 Minuten nur DLR halten und recovern, waehrend dein Partner Druck macht.',
    sparringFocus: 'Zaehle Recoveries und versuche in jeder Runde mehr Recoveries als Verluste zu haben.',
    commonErrors: ['Zu spaet reagieren', 'Kein Frame gegen Brust oder Schulter', 'Winkel verlieren'],
    completionRules: [
      { id: 'watched', label: 'Video angesehen' },
      { id: 'drilled', label: 'Retention-Drill absolviert' },
      { id: 'attempted', label: 'Retention im Sparring getestet' },
    ],
    validationQuestion: 'Woran erkennst du, dass Retention sitzt?',
    validationOptions: [
      'Du kannst den Hook nach Druck wieder herstellen',
      'Du hast sofort einen Sweep',
      'Du liegst flach ohne Frames',
      'Du gibst den Hook auf',
    ],
    validationCorrectAnswer: 'Du kannst den Hook nach Druck wieder herstellen',
  },
  {
    id: 'node-5-dlr-off-balance',
    treeId: 'long-flexible-guard',
    title: 'DLR Off-Balance',
    subtitle: 'Balance des Gegners brechen',
    level: 5,
    track: 'foundation',
    prerequisites: ['node-4-dlr-retention'],
    description: 'Kick, Pull und Winkelarbeit, um den Gegner auf ein Bein zu bringen und Reaktionen zu erzwingen.',
    why: 'Off-Balancing oeffnet Sweep-, Backtake- und Submission-Fenster.',
    successDefinition: ['Gegner kommt auf ein Bein', 'Winkel oeffnet sich', 'Reaktion des Gegners wird lesbar'],
    videos: [
      { title: 'DLR Off Balancing', url: 'https://www.youtube.com/watch?v=VFVwZ4qNfHo', creator: 'Caio Terra' },
      { title: 'DLR Off Balance to Backtake', url: 'https://www.youtube.com/watch?v=Sy5m0Mh0eDg', creator: 'Lachlan Giles' },
    ],
    drill: '3 x 2 Minuten nur Off-Balance erzeugen, ohne direkt den Sweep zu finishen.',
    sparringFocus: 'Breche bewusst die Balance, auch wenn du danach nicht sofort finishst.',
    commonErrors: ['Zu wenig Winkel', 'Zu nah am Gegner', 'Hook beim Pull verlieren'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'drilled', label: 'Off-Balance-Drill absolviert' },
      { id: 'attempted', label: '5 gelungene Off-Balances' },
    ],
    validationQuestion: 'Was ist das Hauptziel von Off-Balance?',
    validationOptions: [
      'Den Gegner auf ein Bein bringen und Reaktionen erzwingen',
      'Sofort den Choke ansetzen',
      'Hook verlieren und resetten',
      'Nur defensiv halten',
    ],
    validationCorrectAnswer: 'Den Gegner auf ein Bein bringen und Reaktionen erzwingen',
  },
  {
    id: 'node-6-dlr-back-exposure',
    treeId: 'long-flexible-guard',
    title: 'DLR to Back Exposure',
    subtitle: 'Rueckenfenster erkennen',
    level: 6,
    track: 'foundation',
    prerequisites: ['node-5-dlr-off-balance'],
    description: 'Du lernst das Timing fuer Rotation hinter die Huefte, sobald der Gegner seine Balance verliert.',
    why: 'Das Rueckenfenster ist kurz. Wer es erkennt, bekommt die beste Submission-Position im Grappling.',
    successDefinition: ['Huefte des Gegners wird hinterlaufen', 'Zwei klare Backtake-Momente entstehen', 'Winkel bleibt erhalten'],
    videos: [{ title: 'DLR to Back Take', url: 'https://www.youtube.com/watch?v=8UCGbKq3Ods', creator: 'John Danaher' }],
    drill: '5 langsame Reps: DLR -> Off-Balance -> Rotation hinter die Huefte.',
    sparringFocus: 'Nur gehen, wenn das Fenster wirklich offen ist. Sonst in der Guard bleiben.',
    commonErrors: ['Zu frueh rotieren', 'Hook vergessen', 'Huefte nicht wirklich hinterlaufen'],
    completionRules: [
      { id: 'watched', label: 'Video angesehen' },
      { id: 'drilled', label: 'Backtake-Drill absolviert' },
      { id: 'attempted', label: '2 Backtake-Versuche im Sparring' },
    ],
  },
  {
    id: 'node-7-back-entry',
    treeId: 'long-flexible-guard',
    title: 'Back Entry',
    subtitle: 'Seatbelt und erster Hook',
    level: 7,
    track: 'foundation',
    prerequisites: ['node-6-dlr-back-exposure'],
    description: 'Aus dem Rueckenfenster wird kontrollierte Back Control: Seatbelt, Hook und Kopfposition.',
    why: 'Viele kommen hinter die Huefte, verlieren aber den Moment vor echter Kontrolle.',
    successDefinition: ['Seatbelt innerhalb von zwei Sekunden', 'Mindestens ein Hook sitzt', 'Gegner bleibt vor dir'],
    videos: [{ title: 'Back Take Entry Mechanics', url: 'https://www.youtube.com/watch?v=qWxiUbANLPY', creator: 'Gordon Ryan' }],
    drill: '3 x 2 Minuten Seatbelt- und Hook-Etablierung aus einer gestarteten Back-Exposure-Situation.',
    sparringFocus: 'Mindestens einen kontrollierten Backtake im Live-Sparring halten.',
    commonErrors: ['Seatbelt zu locker', 'Kopf ausserhalb der Schulterlinie', 'Zu frueh auf den Choke gehen'],
    completionRules: [
      { id: 'watched', label: 'Video angesehen' },
      { id: 'drilled', label: 'Seatbelt-Drill absolviert' },
      { id: 'attempted', label: 'Backtake im Sparring kontrolliert' },
    ],
  },
  {
    id: 'node-8-back-control',
    treeId: 'long-flexible-guard',
    title: 'Back Control',
    subtitle: 'Position vor Submission',
    level: 8,
    track: 'foundation',
    prerequisites: ['node-7-back-entry'],
    description: 'Du stabilisierst Brust-zu-Ruecken-Kontakt, Hooks und Position, bevor du ans Finish denkst.',
    why: 'Die meisten verlieren den Ruecken, weil sie zu frueh den Choke erzwingen.',
    successDefinition: ['10 Sekunden stabile Kontrolle', 'Brustkontakt bleibt konstant', 'Hooks oder Body Triangle bleiben aktiv'],
    videos: [
      { title: 'Back Control Mastery', url: 'https://www.youtube.com/watch?v=TQgjv7lFqXY', creator: 'John Danaher' },
      { title: 'Back Control Stability', url: 'https://www.youtube.com/watch?v=aCfXiE6v5RM', creator: 'Gordon Ryan' },
    ],
    drill: '5 Minuten kontrollieren, waehrend der Partner nur verteidigt und entkommen will.',
    sparringFocus: 'Die ersten 10 Sekunden auf dem Ruecken keine Submission suchen.',
    commonErrors: ['Zu frueh auf den Choke gehen', 'Koerperkontakt verlieren', 'Hooks locker setzen'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'drilled', label: 'Back-Control-Drill absolviert' },
      { id: 'attempted', label: '10 Sekunden Back Control gehalten' },
    ],
  },
  {
    id: 'node-9-rnc-finish',
    treeId: 'long-flexible-guard',
    title: 'RNC Finish',
    subtitle: 'Die Kette sauber abschliessen',
    level: 9,
    track: 'foundation',
    prerequisites: ['node-8-back-control'],
    description: 'Mechanik fuer den Rear Naked Choke aus stabiler Position mit sauberem Choking Arm und Secondary Hand.',
    why: 'Der RNC ist der natuerliche Abschluss deines Win Paths.',
    successDefinition: ['Arm sitzt an der Kehle', 'Secondary Hand schliesst sauber', 'Sauberer Finish-Ansatz im Sparring'],
    videos: [
      { title: 'Rear Naked Choke Mechanics', url: 'https://www.youtube.com/watch?v=gG3JCJgqtbM', creator: 'Gordon Ryan' },
      { title: 'RNC Finish Details', url: 'https://www.youtube.com/watch?v=GVcLQ-6GNCU', creator: 'John Danaher' },
    ],
    drill: '3 technische Serien aus Seatbelt in den RNC. Fokus auf Praezision statt Kraft.',
    sparringFocus: 'Spiele einmal die komplette Kette von Guard ueber Backtake bis zum Finish.',
    commonErrors: ['Zu viel Kraft', 'Arm am Kinn statt an der Kehle', 'Position fuer den Choke opfern'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'drilled', label: 'RNC im Drill sauber ausgefuehrt' },
      { id: 'attempted', label: 'Finish-Ansatz oder Submission im Sparring' },
    ],
  },
  {
    id: 'node-10-kguard-entry',
    treeId: 'long-flexible-guard',
    title: 'K-Guard Entry',
    subtitle: 'Secondary Track',
    level: 4,
    track: 'secondary',
    prerequisites: ['node-3-dlr-connection'],
    description: 'Einstieg in K-Guard als alternativer Entry-Path.',
    why: 'Erweitert dein Guard-Spiel um moderne Bein- und Backtake-Einstiege.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-11-kguard-threats',
    treeId: 'long-flexible-guard',
    title: 'K-Guard Threats',
    subtitle: 'Secondary Track',
    level: 5,
    track: 'secondary',
    prerequisites: ['node-10-kguard-entry'],
    description: 'Angriffsbaum aus K-Guard.',
    why: 'Gibt dir nach dem Entry sofort konkrete Anschlussoptionen.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-12-triangle-entry',
    treeId: 'long-flexible-guard',
    title: 'Triangle Entry',
    subtitle: 'Secondary Track',
    level: 5,
    track: 'secondary',
    prerequisites: ['node-3-dlr-connection'],
    description: 'Triangle als alternativer Win Path aus deinen offenen Guards.',
    why: 'Macht Gegner vorsichtiger und oeffnet dein Backtake-Fenster weiter.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-13-matrix-entry',
    treeId: 'long-flexible-guard',
    title: 'Matrix Entry',
    subtitle: 'Secondary Track',
    level: 6,
    track: 'secondary',
    prerequisites: ['node-11-kguard-threats'],
    description: 'Back-exposure aus Matrix-Positionen.',
    why: 'Fuehrt moderne Guard-Systeme wieder in deinen Haupt-Win-Path zurueck.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-14-5050',
    treeId: 'long-flexible-guard',
    title: '50/50 Recovery',
    subtitle: 'Secondary Track',
    level: 7,
    track: 'secondary',
    prerequisites: ['node-13-matrix-entry'],
    description: 'Kontrollierte 50/50-Zugaenge und Recovery.',
    why: 'Gibt dir einen Sicherheitsanker gegen harte Passer.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-15-torreando',
    treeId: 'long-flexible-guard',
    title: 'Torreando Movement',
    subtitle: 'Top Game Track',
    level: 3,
    track: 'top-game',
    prerequisites: [],
    description: 'Footwork und Griffwechsel fuer mobiles Passing.',
    why: 'Auch Guard-Player brauchen ein klares Top-Game-Backup.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-16-leg-drag',
    treeId: 'long-flexible-guard',
    title: 'Leg Drag Entry',
    subtitle: 'Top Game Track',
    level: 4,
    track: 'top-game',
    prerequisites: ['node-15-torreando'],
    description: 'Leg Drag als technischer Hauptpass.',
    why: 'Passt gut zu deinem mobilen, winkelorientierten Stil.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-17-backstep-pass',
    treeId: 'long-flexible-guard',
    title: 'Backstep Pass',
    subtitle: 'Top Game Track',
    level: 5,
    track: 'top-game',
    prerequisites: ['node-16-leg-drag'],
    description: 'Backstep-Mechanik gegen invertierende Guards.',
    why: 'Wichtig, wenn du selbst moderne Guard-Spieler schlagen willst.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-18-top-backtake',
    treeId: 'long-flexible-guard',
    title: 'Top Backtake',
    subtitle: 'Top Game Track',
    level: 6,
    track: 'top-game',
    prerequisites: ['node-17-backstep-pass'],
    description: 'Rueckenangriffe aus der Top-Position.',
    why: 'Dein Hauptfinish bleibt auch im Top Game derselbe.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-19-top-rnc',
    treeId: 'long-flexible-guard',
    title: 'Top RNC Chain',
    subtitle: 'Top Game Track',
    level: 7,
    track: 'top-game',
    prerequisites: ['node-18-top-backtake'],
    description: 'Top-Game-Kette bis zum Rueckenfinish.',
    why: 'Macht deinen Stil komplett, egal ob du unten oder oben startest.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
]
