export type SkillNode = {
  id: string
  treeId: string
  title: string
  subtitle: string
  level: number
  track: 'foundation' | 'secondary' | 'top-game'
  prerequisites: string[]
  description: string
  why: string
  successDefinition: string[]
  videos: {
    title: string
    url: string
    creator: string
    note?: string
  }[]
  drill: string
  sparringFocus: string
  commonErrors: string[]
  completionRules: {
    id: string
    label: string
  }[]
  validationQuestion?: string
  validationOptions?: string[]
  validationCorrectAnswer?: string
  isComingSoon?: boolean
}

export const LONG_FLEXIBLE_GUARD_TREE: SkillNode[] = [
  {
    id: 'node-1-guard-identity',
    treeId: 'long-flexible-guard',
    title: 'Leg Entry',
    subtitle: 'Guard Pull zu Shin to Shin',
    level: 1,
    track: 'foundation',
    prerequisites: [],
    description: 'Du baust einen sauberen Guard Pull auf, landest direkt in Shin to Shin und verbindest dich sofort mit dem Bein.',
    why: 'Ohne stabilen Leg Entry kommt dein A-Plan gar nicht erst in Gang.',
    successDefinition: ['Guard Pull mit Verbindung', 'Shin to Shin direkt treffen', 'Winkel sofort nach dem Pull sichern'],
    videos: [
      { title: 'Guard Pull to Shin to Shin', url: 'https://www.youtube.com/watch?v=mcU5FBy9n7s', creator: 'YouTube' },
      {
        title: 'Shin-to-Shin Reel',
        url: 'https://www.instagram.com/reel/DTr_HxIiTUj/',
        creator: 'SEBASTIAN ATTARD',
      },
      {
        title: 'Shin-to-Shin Details',
        url: 'https://www.instagram.com/reel/DP5CAGrCBpt/',
        creator: 'Robert Hastings',
      },
      {
        title: 'Simple Shin-to-Shin Entry',
        url: 'https://www.instagram.com/reel/DP6sLXMDs_U/',
        creator: 'Simple Man Martial Arts',
      },
      { title: 'Shin to Shin Guard Pull Concepts', url: 'https://www.youtube.com/watch?v=X3cPYqn-3jM', creator: 'Chewjitsu' },
    ],
    drill: '3 x 2 Minuten Guard Pull in Shin to Shin mit sofortiger Beinverbindung.',
    sparringFocus: 'Suche in jeder Runde zuerst den sauberen Einstieg ans Bein, nicht direkt den Finish.',
    commonErrors: ['Ohne Verbindung fallen', 'Zu weit weg vom Bein landen', 'Kein Winkel nach dem Pull'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'written', label: 'Leg Entry sauber geuebt' },
    ],
    validationQuestion: 'Was ist das Hauptziel von Leg Entry?',
    validationOptions: [
      'Sauber ans Bein kommen und Shin to Shin verbinden',
      'Sofort den Fusshebel reissen',
      'Flach auf dem Ruecken landen',
      'Nur an den Armen ziehen',
    ],
    validationCorrectAnswer: 'Sauber ans Bein kommen und Shin to Shin verbinden',
  },
  {
    id: 'node-2-guard-entry',
    treeId: 'long-flexible-guard',
    title: 'Leg Control',
    subtitle: 'Ashi Garami / Single Leg X',
    level: 2,
    track: 'foundation',
    prerequisites: ['node-1-guard-identity'],
    description: 'Du wandelst den Einstieg in Ashi Garami oder Single Leg X um und fixierst das Bein sauber.',
    why: 'Ohne Leg Control rutscht dir der Gegner aus dem System, bevor du isolieren kannst.',
    successDefinition: ['Knie eng um die Huefte', 'Ferse kontrolliert', 'Gegner auf ein Bein gesetzt'],
    videos: [
      { title: 'Ashi Garami Basics', url: 'https://www.youtube.com/watch?v=TUbGnOKQ2Ck', creator: 'Lachlan Giles' },
      { title: 'Single Leg X Control', url: 'https://www.youtube.com/watch?v=bzCpEblbfDE', creator: 'Gordon Ryan' },
    ],
    drill: '3 x 2 Minuten Ashi Garami aufbauen und die Knie-Linie dabei eng halten.',
    sparringFocus: 'Priorisiere zuerst stabile Kontrolle, bevor du an Isolation oder Finish denkst.',
    commonErrors: ['Fuesse offen lassen', 'Keine Fersenkontrolle', 'Huefte nicht eng genug'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'drilled', label: 'Leg-Control-Drill absolviert' },
      { id: 'attempted', label: 'Leg Control im Sparring versucht' },
    ],
    validationQuestion: 'Was ist der wichtigste Punkt in Leg Control?',
    validationOptions: [
      'Die Knie-Linie und die Ferse sauber kontrollieren',
      'Nur den Fuss anfassen',
      'Sofort rueckwaerts fallen',
      'Das Bein komplett frei lassen',
    ],
    validationCorrectAnswer: 'Die Knie-Linie und die Ferse sauber kontrollieren',
  },
  {
    id: 'node-3-dlr-connection',
    treeId: 'long-flexible-guard',
    title: 'Leg Isolation',
    subtitle: 'Knie-Linie oeffnen',
    level: 3,
    track: 'foundation',
    prerequisites: ['node-2-guard-entry'],
    description: 'Du brichst die Balance, verschiebst das Knie in deine Richtung und isolierst den Fuss fuer den Abschluss.',
    why: 'Isolation entscheidet, ob dein Finish sauber kommt oder der Gegner wieder herausrutscht.',
    successDefinition: ['Knie-Linie frei', 'Off-Balance in die richtige Richtung', 'Fuss sauber isoliert'],
    videos: [
      { title: 'Leg Entanglement Off Balance', url: 'https://www.youtube.com/watch?v=HgmACpVVCQI', creator: 'Bernardo Faria' },
      { title: 'Knee Line Isolation', url: 'https://www.youtube.com/watch?v=9kZpCTRWxq0', creator: 'Mikey Musumeci' },
    ],
    drill: '5 x 2 Minuten Off-Balance in die Bein-Isolation, ohne den Finish zu ueberstuerzen.',
    sparringFocus: 'Schaffe die Isolation sauber, auch wenn du den Finish noch nicht sofort nimmst.',
    commonErrors: ['Nur am Fuss ziehen', 'Keine Gewichtsverlagerung', 'Knie-Linie verlieren'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'drilled', label: 'Isolation-Drill absolviert' },
      { id: 'attempted', label: 'Isolation im Sparring genutzt' },
    ],
    validationQuestion: 'Woran erkennst du gute Leg Isolation?',
    validationOptions: [
      'Die Knie-Linie ist frei und der Fuss bleibt kontrolliert',
      'Der Gegner steht komplett stabil',
      'Du greifst nur mit den Armen',
      'Du gibst die Position sofort auf',
    ],
    validationCorrectAnswer: 'Die Knie-Linie ist frei und der Fuss bleibt kontrolliert',
  },
  {
    id: 'node-4-dlr-retention',
    treeId: 'long-flexible-guard',
    title: 'Knee to Submission',
    subtitle: 'Straight Foot Lock',
    level: 4,
    track: 'foundation',
    prerequisites: ['node-3-dlr-connection'],
    description: 'Du verwandelst die isolierte Knie-Linie in einen sauberen Straight Foot Lock und beendest die Kette kontrolliert.',
    why: 'Der Abschluss muss technisch sauber sein, sonst verschenkst du die ganze Vorarbeit.',
    successDefinition: ['Fersenlinie fixiert', 'Hips unter dem Fuss', 'Druck ueber den ganzen Koerper statt nur ueber die Arme'],
    videos: [{ title: 'Straight Foot Lock Mechanics', url: 'https://www.youtube.com/watch?v=IdXJr3F1AH0', creator: 'Priit Mihkelson' }],
    drill: '3 x 3 Minuten vom isolierten Bein in den kontrollierten Straight Foot Lock abschliessen.',
    sparringFocus: 'Nimm nur den Finish, wenn Kontrolle und Knie-Linie wirklich sitzen.',
    commonErrors: ['Nur mit Armen ziehen', 'Falscher Winkel unterm Fuss', 'Zu frueh aufdrehen'],
    completionRules: [
      { id: 'watched', label: 'Video angesehen' },
      { id: 'drilled', label: 'Submission-Drill absolviert' },
      { id: 'attempted', label: 'Finish im Sparring getestet' },
    ],
    validationQuestion: 'Was macht den Straight Foot Lock hier sauber?',
    validationOptions: [
      'Kontrollierte Knie-Linie plus Druck aus dem ganzen Koerper',
      'Nur maximal an der Ferse ziehen',
      'Sofort ohne Kontrolle nach hinten fallen',
      'Die Position komplett aufmachen',
    ],
    validationCorrectAnswer: 'Kontrollierte Knie-Linie plus Druck aus dem ganzen Koerper',
  },
  {
    id: 'node-5-dlr-off-balance',
    treeId: 'long-flexible-guard',
    title: 'Finish Details',
    subtitle: 'Mehr Druck am Fuss',
    level: 5,
    track: 'foundation',
    prerequisites: ['node-4-dlr-retention'],
    description: 'Hier verfeinerst du Griff, Winkel und Druck, damit dein Straight Foot Lock noch sicherer sitzt.',
    why: 'Kleine Details machen aus einem fast fertigen Finish einen echten Abschluss.',
    successDefinition: ['Grip sitzt tief genug', 'Winkel bleibt geschlossen', 'Druck startet aus den Hips'],
    videos: [
      { title: 'Straight Foot Lock Details', url: 'https://www.youtube.com/watch?v=VFVwZ4qNfHo', creator: 'Caio Terra' },
      { title: 'Breaking Details from Ashi', url: 'https://www.youtube.com/watch?v=Sy5m0Mh0eDg', creator: 'Lachlan Giles' },
    ],
    drill: '3 x 2 Minuten nur Finish-Details nachbauen, bis der Griff und der Winkel jedes Mal gleich sitzen.',
    sparringFocus: 'Achte auf saubere Mechanics statt auf hektische Finishes.',
    commonErrors: ['Zu hoch am Fuss greifen', 'Keine Spannung aus den Hips', 'Winkel vor dem Druck verlieren'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'drilled', label: 'Finish-Details geuebt' },
      { id: 'attempted', label: 'Details im Sparring bewusst angewendet' },
    ],
    validationQuestion: 'Worauf achten Finish Details am meisten?',
    validationOptions: [
      'Auf Griff, Winkel und Hips fuer sauberen Druck',
      'Nur auf Schnelligkeit',
      'Nur auf die Arme',
      'Gar nicht auf die Knie-Linie',
    ],
    validationCorrectAnswer: 'Auf Griff, Winkel und Hips fuer sauberen Druck',
  },
  {
    id: 'node-6-dlr-back-exposure',
    treeId: 'long-flexible-guard',
    title: 'DLR to Back Exposure',
    subtitle: 'Rueckenfenster erkennen',
    level: 6,
    track: 'foundation',
    prerequisites: ['node-5-dlr-off-balance'],
    description: 'Du lernst das Timing fuer Rotation hinter die Huefte, sobald der Gegner seine Balance verliert.',
    why: 'Das Rueckenfenster ist kurz. Wer es erkennt, bekommt die beste Submission-Position im Grappling.',
    successDefinition: ['Huefte des Gegners wird hinterlaufen', 'Zwei klare Backtake-Momente entstehen', 'Winkel bleibt erhalten'],
    videos: [{ title: 'DLR to Back Take', url: 'https://www.youtube.com/watch?v=8UCGbKq3Ods', creator: 'John Danaher' }],
    drill: '5 langsame Reps: DLR -> Off-Balance -> Rotation hinter die Huefte.',
    sparringFocus: 'Nur gehen, wenn das Fenster wirklich offen ist. Sonst in der Guard bleiben.',
    commonErrors: ['Zu frueh rotieren', 'Hook vergessen', 'Huefte nicht wirklich hinterlaufen'],
    completionRules: [
      { id: 'watched', label: 'Video angesehen' },
      { id: 'drilled', label: 'Backtake-Drill absolviert' },
      { id: 'attempted', label: '2 Backtake-Versuche im Sparring' },
    ],
  },
  {
    id: 'node-7-back-entry',
    treeId: 'long-flexible-guard',
    title: 'Back Entry',
    subtitle: 'Seatbelt und erster Hook',
    level: 7,
    track: 'foundation',
    prerequisites: ['node-6-dlr-back-exposure'],
    description: 'Aus dem Rueckenfenster wird kontrollierte Back Control: Seatbelt, Hook und Kopfposition.',
    why: 'Viele kommen hinter die Huefte, verlieren aber den Moment vor echter Kontrolle.',
    successDefinition: ['Seatbelt innerhalb von zwei Sekunden', 'Mindestens ein Hook sitzt', 'Gegner bleibt vor dir'],
    videos: [{ title: 'Back Take Entry Mechanics', url: 'https://www.youtube.com/watch?v=qWxiUbANLPY', creator: 'Gordon Ryan' }],
    drill: '3 x 2 Minuten Seatbelt- und Hook-Etablierung aus einer gestarteten Back-Exposure-Situation.',
    sparringFocus: 'Mindestens einen kontrollierten Backtake im Live-Sparring halten.',
    commonErrors: ['Seatbelt zu locker', 'Kopf ausserhalb der Schulterlinie', 'Zu frueh auf den Choke gehen'],
    completionRules: [
      { id: 'watched', label: 'Video angesehen' },
      { id: 'drilled', label: 'Seatbelt-Drill absolviert' },
      { id: 'attempted', label: 'Backtake im Sparring kontrolliert' },
    ],
  },
  {
    id: 'node-8-back-control',
    treeId: 'long-flexible-guard',
    title: 'Back Control',
    subtitle: 'Position vor Submission',
    level: 8,
    track: 'foundation',
    prerequisites: ['node-7-back-entry'],
    description: 'Du stabilisierst Brust-zu-Ruecken-Kontakt, Hooks und Position, bevor du ans Finish denkst.',
    why: 'Die meisten verlieren den Ruecken, weil sie zu frueh den Choke erzwingen.',
    successDefinition: ['10 Sekunden stabile Kontrolle', 'Brustkontakt bleibt konstant', 'Hooks oder Body Triangle bleiben aktiv'],
    videos: [
      { title: 'Back Control Mastery', url: 'https://www.youtube.com/watch?v=TQgjv7lFqXY', creator: 'John Danaher' },
      { title: 'Back Control Stability', url: 'https://www.youtube.com/watch?v=aCfXiE6v5RM', creator: 'Gordon Ryan' },
    ],
    drill: '5 Minuten kontrollieren, waehrend der Partner nur verteidigt und entkommen will.',
    sparringFocus: 'Die ersten 10 Sekunden auf dem Ruecken keine Submission suchen.',
    commonErrors: ['Zu frueh auf den Choke gehen', 'Koerperkontakt verlieren', 'Hooks locker setzen'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'drilled', label: 'Back-Control-Drill absolviert' },
      { id: 'attempted', label: '10 Sekunden Back Control gehalten' },
    ],
  },
  {
    id: 'node-9-rnc-finish',
    treeId: 'long-flexible-guard',
    title: 'RNC Finish',
    subtitle: 'Die Kette sauber abschliessen',
    level: 9,
    track: 'foundation',
    prerequisites: ['node-8-back-control'],
    description: 'Mechanik fuer den Rear Naked Choke aus stabiler Position mit sauberem Choking Arm und Secondary Hand.',
    why: 'Der RNC ist der natuerliche Abschluss deines Win Paths.',
    successDefinition: ['Arm sitzt an der Kehle', 'Secondary Hand schliesst sauber', 'Sauberer Finish-Ansatz im Sparring'],
    videos: [
      { title: 'Rear Naked Choke Mechanics', url: 'https://www.youtube.com/watch?v=gG3JCJgqtbM', creator: 'Gordon Ryan' },
      { title: 'RNC Finish Details', url: 'https://www.youtube.com/watch?v=GVcLQ-6GNCU', creator: 'John Danaher' },
    ],
    drill: '3 technische Serien aus Seatbelt in den RNC. Fokus auf Praezision statt Kraft.',
    sparringFocus: 'Spiele einmal die komplette Kette von Guard ueber Backtake bis zum Finish.',
    commonErrors: ['Zu viel Kraft', 'Arm am Kinn statt an der Kehle', 'Position fuer den Choke opfern'],
    completionRules: [
      { id: 'watched', label: 'Videos angesehen' },
      { id: 'drilled', label: 'RNC im Drill sauber ausgefuehrt' },
      { id: 'attempted', label: 'Finish-Ansatz oder Submission im Sparring' },
    ],
  },
  {
    id: 'node-10-kguard-entry',
    treeId: 'long-flexible-guard',
    title: 'K-Guard Entry',
    subtitle: 'Secondary Track',
    level: 4,
    track: 'secondary',
    prerequisites: ['node-3-dlr-connection'],
    description: 'Einstieg in K-Guard als alternativer Entry-Path.',
    why: 'Erweitert dein Guard-Spiel um moderne Bein- und Backtake-Einstiege.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-11-kguard-threats',
    treeId: 'long-flexible-guard',
    title: 'K-Guard Threats',
    subtitle: 'Secondary Track',
    level: 5,
    track: 'secondary',
    prerequisites: ['node-10-kguard-entry'],
    description: 'Angriffsbaum aus K-Guard.',
    why: 'Gibt dir nach dem Entry sofort konkrete Anschlussoptionen.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-12-triangle-entry',
    treeId: 'long-flexible-guard',
    title: 'Triangle Entry',
    subtitle: 'Secondary Track',
    level: 5,
    track: 'secondary',
    prerequisites: ['node-3-dlr-connection'],
    description: 'Triangle als alternativer Win Path aus deinen offenen Guards.',
    why: 'Macht Gegner vorsichtiger und oeffnet dein Backtake-Fenster weiter.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-13-matrix-entry',
    treeId: 'long-flexible-guard',
    title: 'Matrix Entry',
    subtitle: 'Secondary Track',
    level: 6,
    track: 'secondary',
    prerequisites: ['node-11-kguard-threats'],
    description: 'Back-exposure aus Matrix-Positionen.',
    why: 'Fuehrt moderne Guard-Systeme wieder in deinen Haupt-Win-Path zurueck.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-14-5050',
    treeId: 'long-flexible-guard',
    title: '50/50 Recovery',
    subtitle: 'Secondary Track',
    level: 7,
    track: 'secondary',
    prerequisites: ['node-13-matrix-entry'],
    description: 'Kontrollierte 50/50-Zugaenge und Recovery.',
    why: 'Gibt dir einen Sicherheitsanker gegen harte Passer.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-15-torreando',
    treeId: 'long-flexible-guard',
    title: 'Torreando Movement',
    subtitle: 'Top Game Track',
    level: 3,
    track: 'top-game',
    prerequisites: [],
    description: 'Footwork und Griffwechsel fuer mobiles Passing.',
    why: 'Auch Guard-Player brauchen ein klares Top-Game-Backup.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-16-leg-drag',
    treeId: 'long-flexible-guard',
    title: 'Leg Drag Entry',
    subtitle: 'Top Game Track',
    level: 4,
    track: 'top-game',
    prerequisites: ['node-15-torreando'],
    description: 'Leg Drag als technischer Hauptpass.',
    why: 'Passt gut zu deinem mobilen, winkelorientierten Stil.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-17-backstep-pass',
    treeId: 'long-flexible-guard',
    title: 'Backstep Pass',
    subtitle: 'Top Game Track',
    level: 5,
    track: 'top-game',
    prerequisites: ['node-16-leg-drag'],
    description: 'Backstep-Mechanik gegen invertierende Guards.',
    why: 'Wichtig, wenn du selbst moderne Guard-Spieler schlagen willst.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-18-top-backtake',
    treeId: 'long-flexible-guard',
    title: 'Top Backtake',
    subtitle: 'Top Game Track',
    level: 6,
    track: 'top-game',
    prerequisites: ['node-17-backstep-pass'],
    description: 'Rueckenangriffe aus der Top-Position.',
    why: 'Dein Hauptfinish bleibt auch im Top Game derselbe.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
  {
    id: 'node-19-top-rnc',
    treeId: 'long-flexible-guard',
    title: 'Top RNC Chain',
    subtitle: 'Top Game Track',
    level: 7,
    track: 'top-game',
    prerequisites: ['node-18-top-backtake'],
    description: 'Top-Game-Kette bis zum Rueckenfinish.',
    why: 'Macht deinen Stil komplett, egal ob du unten oder oben startest.',
    successDefinition: [],
    videos: [],
    drill: '',
    sparringFocus: '',
    commonErrors: [],
    completionRules: [],
    isComingSoon: true,
  },
]
